services:
    BowlOfSoup\CouchbaseMigrationsBundle\Command\CreateBucketCommand:
        class: BowlOfSoup\CouchbaseMigrationsBundle\Command\CreateBucketCommand
        arguments:
        - '@BowlOfSoup\CouchbaseMigrationsBundle\Factory\ClusterFactory'
        - %couchbase_migrations.user%
        - %couchbase_migrations.password%
        - %couchbase_migrations.bucket_default%
        tags:
        - { name: 'console.command' }

    BowlOfSoup\CouchbaseMigrationsBundle\Command\ExecuteCommand:
      class: BowlOfSoup\CouchbaseMigrationsBundle\Command\ExecuteCommand
      arguments:
        - %kernel.project_dir%
        - '@BowlOfSoup\CouchbaseMigrationsBundle\Factory\ClusterFactory'
      tags:
        - { name: 'console.command' }

    BowlOfSoup\CouchbaseMigrationsBundle\Command\FlushDataCommand:
      class: BowlOfSoup\CouchbaseMigrationsBundle\Command\FlushDataCommand
      arguments:
        - '@BowlOfSoup\CouchbaseMigrationsBundle\Factory\ClusterFactory'
      tags:
        - { name: 'console.command' }

    BowlOfSoup\CouchbaseMigrationsBundle\Command\GenerateCommand:
      class: BowlOfSoup\CouchbaseMigrationsBundle\Command\GenerateCommand
      arguments:
        - %kernel.project_dir%
      tags:
        - { name: 'console.command' }

    BowlOfSoup\CouchbaseMigrationsBundle\Command\MigrateCommand:
      class: BowlOfSoup\CouchbaseMigrationsBundle\Command\MigrateCommand
      arguments:
        - %kernel.project_dir%
        - %couchbase_migrations.bucket_migrations%
        - '@BowlOfSoup\CouchbaseMigrationsBundle\Factory\ClusterFactory'
      tags:
        - { name: 'console.command' }

    BowlOfSoup\CouchbaseMigrationsBundle\Command\RemoveBucketCommand:
        class: BowlOfSoup\CouchbaseMigrationsBundle\Command\RemoveBucketCommand
        arguments:
        - '@BowlOfSoup\CouchbaseMigrationsBundle\Factory\ClusterFactory'
        - %couchbase_migrations.user%
        - %couchbase_migrations.password%
        - %couchbase_migrations.bucket_default%
        tags:
        - { name: 'console.command' }

    BowlOfSoup\CouchbaseMigrationsBundle\Factory\ClusterFactory:
      class: BowlOfSoup\CouchbaseMigrationsBundle\Factory\ClusterFactory
      arguments:
        - '@BowlOfSoup\CouchbaseMigrationsBundle\Model\ConnectionSettings'
        - %couchbase_migrations.bucket_default%

    BowlOfSoup\CouchbaseMigrationsBundle\Model\ConnectionSettings:
      class: BowlOfSoup\CouchbaseMigrationsBundle\Model\ConnectionSettings
      arguments:
        - %couchbase_migrations.host%
        - %couchbase_migrations.user%
        - %couchbase_migrations.password%